create schema if not exists shop;

drop table if exists shop.product;

create table shop.product (
    identifier integer generated by default as identity(
        start with 1 increment by 1) primary key,
        name varchar(50),
        price integer
);